[theme]
base = "dark"
primaryColor = "#BEB7A4"  # Khaki
backgroundColor = "#0E1117" # Rich black
secondaryBackgroundColor = "#262730" # Raisin black
textColor = "#FFFFFC" # Baby powder
font = "sans serif"